### ISSUE TITLE
method is not supported

### ISSUE THREAD

**Issue by rjoydip-zz** [medleyjs/medley#2] opened 2018-05-01 18:24 UTC
Getting error:
``` throw new RangeError(`"${method}" method is not supported`)```
Example: (***where method is a blank string***)
```js
app.route({
    method: '',
    path: '/',
    responseSchema: {
      200: {
        hello: { type: 'string' }
      }
    },
    handler: function(req, res) {
      res.send({ hello: 'world' });
    }
  })
```

**Comment by nwoltman** [comment] 2018-05-01 18:43
I'm not exactly sure what the problem is here. This is expected because the empty string `''` is not a valid method. Only methods in the `http.METHODS` array are supported:

```js
console.log(require('http').METHODS)
```

Here's what I get when I try using the empty string:

```sh
> node -e "require('@medley/medley')().route({method: ''})"
C:\GitHub\medley\medley.js:290
        throw new RangeError(`"${method}" method is not supported`)
        ^

RangeError: "" method is not supported
    at Object.route (C:\GitHub\medley\medley.js:290:15)
    at [eval]:1:17
    at Script.runInThisContext (vm.js:65:33)
    at Object.runInThisContext (vm.js:197:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at evalScript (internal/bootstrap/node.js:483:27)
    at startup (internal/bootstrap/node.js:177:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

The error message is `"" method is not supported` which I'm hoping is clear enough.

**Comment by nwoltman** [comment] 2018-05-04 02:56
Closing as this is working as expected. Please re-open if this is not the case.

**Closed as completed by nwoltman** 2018-05-04 02:56 UTC
